// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartShortcuts.Models;

#nullable disable

namespace SmartShortcuts.Migrations
{
    [DbContext(typeof(ShortcutsContext))]
    [Migration("20230607140208_ShortcutUpdate")]
    partial class ShortcutUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("ActionShortcut", b =>
                {
                    b.Property<string>("ActionsID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortcutsID")
                        .HasColumnType("TEXT");

                    b.HasKey("ActionsID", "ShortcutsID");

                    b.HasIndex("ShortcutsID");

                    b.ToTable("ActionShortcut");
                });

            modelBuilder.Entity("SmartShortcuts.Models.Action", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("SmartShortcuts.Models.Shortcut", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortcutKeys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Shortcuts");
                });

            modelBuilder.Entity("ActionShortcut", b =>
                {
                    b.HasOne("SmartShortcuts.Models.Action", null)
                        .WithMany()
                        .HasForeignKey("ActionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartShortcuts.Models.Shortcut", null)
                        .WithMany()
                        .HasForeignKey("ShortcutsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
